### ISSUE TITLE
How to disable the function to print information?

### ISSUE THREAD

**Issue by shengzeang** [PKU-DAIR/open-box#6]
The project is wonderful! It helps me a lot! But I don't know how to disable the function to print information, i.e.
![image](https://user-images.githubusercontent.com/72069497/145195390-f79a6c83-0eed-48e4-afec-29373c802b60.png)

I don't want to print the information which makes my results hard to observe. So is there any method to solve it?

**Comment by jhj0411jhj** [comment]
Thanks for the issue! We apologize that there's no button to switch off the logging information so far. We will add a parameter to control the logger in the following version.

To solve the problem in the current version, we suggest:
1. Download the project.
2. Filter the information by modifying the configuration file `logging.yaml` under `openbox/utils/`.
```yaml
---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '[%(levelname)s] [%(asctime)s] [%(name)s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: open-box.log

root:
  level: DEBUG
  handlers: [console, file_handler]
```
Change the logging level in Line 11 from `INFO` to `ERROR`.
3. Uninstall the current version of OpenBox.
4. Run `python setup.py install` under the root directory of the project to reinstall OpenBox. 

In this way, all messages that start with `[INFO]` will be filtered.
